apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditcheckservice 
spec:
  selector:
    matchLabels:
      app: creditcheckservice
  template:
    metadata:
      labels:
        app: creditcheckservice
    spec:
      tolerations:
      nodeSelector:
      terminationGracePeriodSeconds: 5
      containers:
      - name: creditcheckservice
        image: docker.io/library/credit-check-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
        env:
        - name: PORT
          value: "8888"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: "creditcheckservice"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=qep,service.version=1.3"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage,b3multi"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(NODE_IP):4317"
        - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
          value: "true"
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            cpu: 110m
            memory: 90Mi
          limits:
            cpu: 130m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: creditcheckservice
spec:
  type: ClusterIP
  selector:
    app: creditcheckservice
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888